/**
 * Shared SEO path list and Render/Netlify-style _redirects rules.
 * Slashless URLs must 301 to trailing-slash shells so crawlers never hit SPA homepage canonical.
 */
const path = require('path');
const { pathToFileURL } = require('url');

const { SERVICE_PAGES, SERVICE_PAGE_ORDER } = require('../src/data/servicePages');
const { CITY_PAGES, CITY_PAGE_ORDER } = require('../src/data/cityPages');
const { GUIDE_PAGES, GUIDE_PAGE_ORDER } = require('../src/data/guidePages');
const { PROJECT_PAGES, PROJECT_PAGE_ORDER } = require('../src/data/projectPages');

/** Marketplace routes — noindex shells; still get slashless → slash redirects. */
const NOINDEX_SHELL_PATHS = [
  { path: '/contractor-login', title: 'Contractor Login | LoomiHome Patios' },
  { path: '/admin-login', title: 'Admin Login | LoomiHome Patios' },
  { path: '/lobby', title: 'Lead Lobby | LoomiHome Patios' },
  { path: '/account', title: 'Account | LoomiHome Patios' },
  { path: '/admin-leads', title: 'Admin | LoomiHome Patios' },
];

async function loadCityServiceData() {
  const mod = await import(
    pathToFileURL(path.join(__dirname, '../src/data/cityServicePages.js')).href
  );
  return {
    CITY_SERVICE_PAGES: mod.CITY_SERVICE_PAGES,
    CITY_SERVICE_PAGE_ORDER: mod.CITY_SERVICE_PAGE_ORDER,
  };
}

function collectSeoPaths(cityService) {
  const { CITY_SERVICE_PAGES, CITY_SERVICE_PAGE_ORDER } = cityService;
  const paths = ['/'];
  SERVICE_PAGE_ORDER.forEach((key) => paths.push(SERVICE_PAGES[key].path));
  CITY_PAGE_ORDER.forEach((id) => paths.push(CITY_PAGES[id].path));
  CITY_SERVICE_PAGE_ORDER.forEach((id) => paths.push(CITY_SERVICE_PAGES[id].path));
  GUIDE_PAGE_ORDER.forEach((id) => paths.push(GUIDE_PAGES[id].path));
  PROJECT_PAGE_ORDER.forEach((id) => paths.push(PROJECT_PAGES[id].path));
  return [...new Set(paths)];
}

/** Build _redirects contents for Render static hosting (Netlify-style). */
function buildRedirectsFile(seoPaths) {
  const fs = require('fs');
  const lines = [
    '# Generated by scripts/seoRedirects.js — do not edit by hand',
    '/sitemap.xml /sitemap.xml 200',
    '/robots.txt /robots.txt 200',
    '/llms.txt /llms.txt 200',
    '/BingSiteAuth.xml /BingSiteAuth.xml 200',
    '/.well-known/llms.txt /.well-known/llms.txt 200',
    '/og/og-aluminum.jpg /og/og-aluminum.jpg 200',
    '/og/og-glass.jpg /og/og-glass.jpg 200',
    '/og/og-skyline.jpg /og/og-skyline.jpg 200',
    '/og/og-sunrooms.jpg /og/og-sunrooms.jpg 200',
    '/contractor /contractor-login 301',
  ];

  let indexNowKey = '';
  try {
    const configPath = path.join(__dirname, '..', 'src', 'data', 'indexNow.json');
    const { key } = JSON.parse(fs.readFileSync(configPath, 'utf8'));
    indexNowKey = String(key || '').trim();
  } catch {
    indexNowKey = '';
  }
  if (indexNowKey) {
    lines.push(`/${indexNowKey}.txt /${indexNowKey}.txt 200`);
  }

  // 301! forces redirect before SPA fallback — critical for SEO canonical consistency.
  seoPaths
    .filter((pathname) => pathname !== '/')
    .forEach((pathname) => {
      lines.push(`${pathname} ${pathname}/ 301!`);
    });

  NOINDEX_SHELL_PATHS.forEach(({ path: pathname }) => {
    lines.push(`${pathname} ${pathname}/ 301!`);
  });

  // SPA fallback — must be last.
  lines.push('/* /index.html 200');

  return `${lines.join('\n')}\n`;
}

async function collectAllSeoPaths() {
  const cityService = await loadCityServiceData();
  return collectSeoPaths(cityService);
}

module.exports = {
  NOINDEX_SHELL_PATHS,
  loadCityServiceData,
  collectSeoPaths,
  collectAllSeoPaths,
  buildRedirectsFile,
};
