/**
 * Shared SEO path list + redirect helpers.
 * Render static sites do NOT honor Netlify `_redirects` — use Blueprint `routes`
 * in render.yaml (synced by scripts/generate-redirects.js).
 */
const path = require('path');
const { pathToFileURL } = require('url');

const { SERVICE_PAGES, SERVICE_PAGE_ORDER } = require('../src/data/servicePages');
const { CITY_PAGES, CITY_PAGE_ORDER } = require('../src/data/cityPages');
const { GUIDE_PAGES, GUIDE_PAGE_ORDER } = require('../src/data/guidePages');
const { PROJECT_PAGES, PROJECT_PAGE_ORDER } = require('../src/data/projectPages');

/** Marketplace routes — noindex shells; still get slashless → slash redirects. */
const NOINDEX_SHELL_PATHS = [
  { path: '/contractor-login', title: 'Contractor Login | LoomiHome Patios' },
  { path: '/admin-login', title: 'Admin Login | LoomiHome Patios' },
  { path: '/lobby', title: 'Lead Lobby | LoomiHome Patios' },
  { path: '/account', title: 'Account | LoomiHome Patios' },
  { path: '/admin-leads', title: 'Admin | LoomiHome Patios' },
];

async function loadCityServiceData() {
  const mod = await import(
    pathToFileURL(path.join(__dirname, '../src/data/cityServicePages.js')).href
  );
  return {
    CITY_SERVICE_PAGES: mod.CITY_SERVICE_PAGES,
    CITY_SERVICE_PAGE_ORDER: mod.CITY_SERVICE_PAGE_ORDER,
  };
}

function collectSeoPaths(cityService) {
  const { CITY_SERVICE_PAGES, CITY_SERVICE_PAGE_ORDER } = cityService;
  const paths = ['/'];
  SERVICE_PAGE_ORDER.forEach((key) => paths.push(SERVICE_PAGES[key].path));
  CITY_PAGE_ORDER.forEach((id) => paths.push(CITY_PAGES[id].path));
  CITY_SERVICE_PAGE_ORDER.forEach((id) => paths.push(CITY_SERVICE_PAGES[id].path));
  GUIDE_PAGE_ORDER.forEach((id) => paths.push(GUIDE_PAGES[id].path));
  PROJECT_PAGE_ORDER.forEach((id) => paths.push(PROJECT_PAGES[id].path));
  return [...new Set(paths)];
}

/** Netlify-style _redirects mirror (not used by Render — kept for tooling/docs). */
function buildRedirectsFile(seoPaths) {
  const fs = require('fs');
  const lines = [
    '# Generated by scripts/seoRedirects.js — Netlify-style mirror only.',
    '# Render IGNORES this file (it is served as a static asset).',
    '# Real slashless redirects: render.yaml routes (synced by generate-redirects.js).',
    '/sitemap.xml /sitemap.xml 200',
    '/robots.txt /robots.txt 200',
    '/llms.txt /llms.txt 200',
    '/BingSiteAuth.xml /BingSiteAuth.xml 200',
    '/.well-known/llms.txt /.well-known/llms.txt 200',
    '/og/og-aluminum.jpg /og/og-aluminum.jpg 200',
    '/og/og-glass.jpg /og/og-glass.jpg 200',
    '/og/og-skyline.jpg /og/og-skyline.jpg 200',
    '/og/og-sunrooms.jpg /og/og-sunrooms.jpg 200',
    '/contractor /contractor-login 301',
  ];

  let indexNowKey = '';
  try {
    const configPath = path.join(__dirname, '..', 'src', 'data', 'indexNow.json');
    const { key } = JSON.parse(fs.readFileSync(configPath, 'utf8'));
    indexNowKey = String(key || '').trim();
  } catch {
    indexNowKey = '';
  }
  if (indexNowKey) {
    lines.push(`/${indexNowKey}.txt /${indexNowKey}.txt 200`);
  }

  seoPaths
    .filter((pathname) => pathname !== '/')
    .forEach((pathname) => {
      lines.push(`${pathname} ${pathname}/ 301`);
    });

  NOINDEX_SHELL_PATHS.forEach(({ path: pathname }) => {
    lines.push(`${pathname} ${pathname}/ 301`);
  });

  lines.push('/* /index.html 200');
  return `${lines.join('\n')}\n`;
}

/** Render Blueprint routes — slashless → trailing slash, then SPA rewrite. */
function buildRenderRoutes(seoPaths) {
  const routes = [];

  seoPaths
    .filter((pathname) => pathname !== '/')
    .forEach((pathname) => {
      routes.push({
        type: 'redirect',
        source: pathname,
        destination: `${pathname}/`,
      });
    });

  NOINDEX_SHELL_PATHS.forEach(({ path: pathname }) => {
    routes.push({
      type: 'redirect',
      source: pathname,
      destination: `${pathname}/`,
    });
  });

  routes.push({
    type: 'rewrite',
    source: '/*',
    destination: '/index.html',
  });

  return routes;
}

function formatRenderRoutesYaml(routes, indent = '    ') {
  const lines = [`${indent}routes:`];
  routes.forEach((route) => {
    lines.push(`${indent}  - type: ${route.type}`);
    lines.push(`${indent}    source: ${route.source}`);
    lines.push(`${indent}    destination: ${route.destination}`);
  });
  return lines.join('\n');
}

/**
 * Inject/replace routes under the loomihome-patios static service in render.yaml.
 */
function syncRenderYamlRoutes(renderYamlText, routesYamlBlock) {
  const markerStart = '    # BEGIN GENERATED SEO ROUTES';
  const markerEnd = '    # END GENERATED SEO ROUTES';
  const block = `${markerStart}\n${routesYamlBlock}\n${markerEnd}`;

  if (renderYamlText.includes(markerStart) && renderYamlText.includes(markerEnd)) {
    return renderYamlText.replace(
      new RegExp(`${markerStart}[\\s\\S]*?${markerEnd}`),
      block,
    );
  }

  // First-time inject: after staticPublishPath / before autoDeploy on loomihome-patios.
  const serviceNeedle = '    name: loomihome-patios';
  const idx = renderYamlText.indexOf(serviceNeedle);
  if (idx === -1) {
    throw new Error('Could not find loomihome-patios service in render.yaml');
  }

  const afterService = renderYamlText.slice(idx);
  const autoDeployMatch = afterService.match(/\n    autoDeploy:\s*true\b/);
  if (!autoDeployMatch) {
    throw new Error('Could not find autoDeploy under loomihome-patios in render.yaml');
  }

  const insertAt = idx + autoDeployMatch.index;
  return (
    `${renderYamlText.slice(0, insertAt)}\n${block}\n${renderYamlText.slice(insertAt)}`
  );
}

async function collectAllSeoPaths() {
  const cityService = await loadCityServiceData();
  return collectSeoPaths(cityService);
}

module.exports = {
  NOINDEX_SHELL_PATHS,
  loadCityServiceData,
  collectSeoPaths,
  collectAllSeoPaths,
  buildRedirectsFile,
  buildRenderRoutes,
  formatRenderRoutesYaml,
  syncRenderYamlRoutes,
};
